# Generated by Django 4.1.4 on 2022-12-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_create_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
