# Generated by Django 4.1.4 on 2022-12-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_on',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='cuerpo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
