# Generated by Django 4.1.4 on 2022-12-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_author_post_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cuerpo',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creado_en',
            new_name='create_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
    ]
