# Generated by Django 4.1.4 on 2022-12-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_create_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
